/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashRouteImport } from './routes/dash'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashIndexRouteImport } from './routes/dash/index'
import { Route as DashSettingsRouteImport } from './routes/dash/settings'
import { Route as DashTunnelsIndexRouteImport } from './routes/dash/tunnels/index'
import { Route as DashTunnelsTunnelIdRouteImport } from './routes/dash/tunnels/$tunnelId'

const DashRoute = DashRouteImport.update({
  id: '/dash',
  path: '/dash',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashIndexRoute = DashIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashRoute,
} as any)
const DashSettingsRoute = DashSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashRoute,
} as any)
const DashTunnelsIndexRoute = DashTunnelsIndexRouteImport.update({
  id: '/tunnels/',
  path: '/tunnels/',
  getParentRoute: () => DashRoute,
} as any)
const DashTunnelsTunnelIdRoute = DashTunnelsTunnelIdRouteImport.update({
  id: '/tunnels/$tunnelId',
  path: '/tunnels/$tunnelId',
  getParentRoute: () => DashRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dash': typeof DashRouteWithChildren
  '/dash/settings': typeof DashSettingsRoute
  '/dash/': typeof DashIndexRoute
  '/dash/tunnels/$tunnelId': typeof DashTunnelsTunnelIdRoute
  '/dash/tunnels': typeof DashTunnelsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dash/settings': typeof DashSettingsRoute
  '/dash': typeof DashIndexRoute
  '/dash/tunnels/$tunnelId': typeof DashTunnelsTunnelIdRoute
  '/dash/tunnels': typeof DashTunnelsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dash': typeof DashRouteWithChildren
  '/dash/settings': typeof DashSettingsRoute
  '/dash/': typeof DashIndexRoute
  '/dash/tunnels/$tunnelId': typeof DashTunnelsTunnelIdRoute
  '/dash/tunnels/': typeof DashTunnelsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dash'
    | '/dash/settings'
    | '/dash/'
    | '/dash/tunnels/$tunnelId'
    | '/dash/tunnels'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dash/settings'
    | '/dash'
    | '/dash/tunnels/$tunnelId'
    | '/dash/tunnels'
  id:
    | '__root__'
    | '/'
    | '/dash'
    | '/dash/settings'
    | '/dash/'
    | '/dash/tunnels/$tunnelId'
    | '/dash/tunnels/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashRoute: typeof DashRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dash': {
      id: '/dash'
      path: '/dash'
      fullPath: '/dash'
      preLoaderRoute: typeof DashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dash/': {
      id: '/dash/'
      path: '/'
      fullPath: '/dash/'
      preLoaderRoute: typeof DashIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/settings': {
      id: '/dash/settings'
      path: '/settings'
      fullPath: '/dash/settings'
      preLoaderRoute: typeof DashSettingsRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/tunnels/': {
      id: '/dash/tunnels/'
      path: '/tunnels'
      fullPath: '/dash/tunnels'
      preLoaderRoute: typeof DashTunnelsIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/tunnels/$tunnelId': {
      id: '/dash/tunnels/$tunnelId'
      path: '/tunnels/$tunnelId'
      fullPath: '/dash/tunnels/$tunnelId'
      preLoaderRoute: typeof DashTunnelsTunnelIdRouteImport
      parentRoute: typeof DashRoute
    }
  }
}

interface DashRouteChildren {
  DashSettingsRoute: typeof DashSettingsRoute
  DashIndexRoute: typeof DashIndexRoute
  DashTunnelsTunnelIdRoute: typeof DashTunnelsTunnelIdRoute
  DashTunnelsIndexRoute: typeof DashTunnelsIndexRoute
}

const DashRouteChildren: DashRouteChildren = {
  DashSettingsRoute: DashSettingsRoute,
  DashIndexRoute: DashIndexRoute,
  DashTunnelsTunnelIdRoute: DashTunnelsTunnelIdRoute,
  DashTunnelsIndexRoute: DashTunnelsIndexRoute,
}

const DashRouteWithChildren = DashRoute._addFileChildren(DashRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashRoute: DashRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
